### ISSUE TITLE
FavoriteItem Entity data count is different

### ISSUE THREAD

**Issue by oddukgi** [sunmiya5/Gasungbi#1]
![3573f0d8-1708-4ca7-ac0b-eb2156b7b1c0-original](https://user-images.githubusercontent.com/3068049/70122780-97819e00-16b4-11ea-9720-3572bff697c9.png)

### Log
```
1
3
4
3

마하링크 DVI- D 싱글
Optional(4) //--> problem
리버네트워크 넥시 DVI- D 듀얼 케이블
Optional(4)
강원전자 넷메이트 DVI- D 듀얼 골드 메탈 케이블
Optional(4)
Optional(4)
```
I select 3 items, FavoriteItemVC count four items.

**Comment by sunmiya5** [comment]
Solution 
- [ ] change data model
- [ ] change code
- [ ] test

**Comment by oddukgi** [comment]
I misunderstand TableView code, and change data model.

**Comment by oddukgi** [comment]
## Problem 
created the favorites object 2 times. One in FavoritesCoreData
`var favorites = Favorites(context: context)`
and in the same function, you are making a call to `SearchItemCoreData.shared.addFavoriteItem`.
This method also create a new object of Favorites
`let item = Favorites(context: context)`
## Sol
- change code create Core Data once and save data
