### ISSUE TITLE
Price Info View show Empty

### ISSUE THREAD

**Issue by oddukgi** [sunmiya5/Gasungbi#4]
## Problem
![EmptyView](https://user-images.githubusercontent.com/3068049/70726111-e8dafe80-1d40-11ea-9a5d-a9b40f6366f6.gif)

1) The Price Info view shows empty in all cases and that can give the mistaken impression that the app is not working.
2) When Favorites button pushed, show pop-up 

## Solution 

1) Apply on [WebViewWarmUper](https://github.com/bernikovich/WebViewWarmUper)
-  Reference
[WkWebView renders slow](https://stackoverflow.com/questions/26684558/tactics-to-speed-up-wkwebview-rendering-of-loadhtmlstring-d-content
)
2) Test loading website using VPN  --> Slow
I switch other country IP address to test loading.
**USA, EU country internet speed is slow.**
**Singapore is quite slow (not slow than USA)**
## Performance (loading website)
Korea : 0.9476 sec
LA : 8.1920 sec
Germany : 19.886 sec
Singapore : 15.4936 sec

**Comment by sunmiya5** [comment]
I did test changing IP address with VPN program.
It doesn't affect. WKWebView renders slowly from external URL.

**Comment by oddukgi** [comment]
## load webpage from different IP address

<p float="left">
 <figcaption><b>1. Arizona</b></figcaption>  
  <img src="https://user-images.githubusercontent.com/3068049/70848940-ef41b580-1ebb-11ea-825e-5d8572357760.gif"/>
 &nbsp;
 <figcaption><b>2. Germany</b></figcaption>  
 <img src="https://user-images.githubusercontent.com/3068049/70848958-0c768400-1ebc-11ea-8965-38b8f8b9343c.gif"/> 
 &nbsp;
 <figcaption><b>3. Singapore</b></figcaption>  
 <img src="https://user-images.githubusercontent.com/3068049/70849096-64fa5100-1ebd-11ea-93b1-008d88456979.gif"/> 
</p>
 &nbsp;

**Comment by sunmiya5** [comment]
## Germany
![germany](https://user-images.githubusercontent.com/3068049/70848738-48f4b080-1eb9-11ea-9e57-e160227a21cd.gif)

**Comment by sunmiya5** [comment]
USA LA loading website speed : 2.0450871666689636 sec
